In [35]:
import numpy as np
audio_data = np.load('C:/Users/o/Desktop/audio_project/Tacotron-2/training_data/audio/audio-LJ002-0001.npy')

In [36]:
len(audio_data)

177375

In [37]:
audio_data.shape


(177375,)

In [38]:
209550/762

275.0

In [39]:
audio_data

array([ 0.00721573,  0.00398583, -0.00137442, ..., -0.01999787,
       -0.01786751, -0.01628692], dtype=float32)

In [40]:
linear_data = np.load('C:/Users/o/Desktop/audio_project/Tacotron-2/training_data/linear/linear-LJ002-0001.npy')

In [41]:
linear_data

array([[ 0.29987812,  0.30229902,  0.31278372, ..., -0.18832326,
        -0.19199276, -0.19084525],
       [-0.20061684, -0.1708231 , -0.1661675 , ..., -0.7151141 ,
        -0.6729424 , -0.6338911 ],
       [-2.2568736 , -2.5581932 , -2.7559438 , ..., -2.2639294 ,
        -2.1712804 , -2.1575787 ],
       ...,
       [-2.9319873 , -2.6455226 , -2.254193  , ..., -3.5383942 ,
        -3.7491565 , -4.        ],
       [-0.54520845, -0.553025  , -0.5673218 , ..., -3.2018895 ,
        -3.627592  , -4.        ],
       [ 0.14086628,  0.1321044 ,  0.12004995, ..., -2.860877  ,
        -2.900899  , -2.9495587 ]], dtype=float32)

In [42]:
linear_data.shape

(645, 1025)

In [43]:
len(linear_data)

645

In [48]:
mel_data = np.load('C:/Users/o/Desktop/audio_project/Tacotron-2/training_data/mels/mel-LJ002-0001.npy')

In [49]:
mel_data

array([[-1.1346476 , -0.86543906, -0.9011537 , ..., -1.3873132 ,
        -1.48133   , -1.3600652 ],
       [-1.5305859 , -0.8136612 , -0.71953464, ..., -0.9945502 ,
        -0.2595733 , -0.06507984],
       [-1.7287418 , -0.80089784, -0.5129053 , ..., -0.6459155 ,
         0.07374536,  0.27179644],
       ...,
       [-2.1178117 , -1.6046498 , -0.8575118 , ..., -2.6536129 ,
        -2.4669414 , -2.6651144 ],
       [-2.2094164 , -2.1288865 , -1.4633856 , ..., -2.410168  ,
        -2.3676436 , -2.6023536 ],
       [-1.688476  , -2.0089624 , -1.040856  , ..., -2.5614288 ,
        -2.5446668 , -2.756523  ]], dtype=float32)

In [50]:
len(mel_data)
mel_data.shape

(645, 80)